server:
  port: ${SERVER_PORT:8099}
  servlet.context-path: ${SERVER_CONTEXT-PATH:/api/school-project}
  compression.enabled: true
  error.include-message: always
  spring.url: ${SERVER_SPRING_URL:localhost:8099}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5445/school_project?currentSchema=public}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driverClassName: org.postgresql.Driver
    driver: org.postgresql.Driver
    connection-from: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.format_sql: true
  liquibase:
    enabled: true
    default-schema: public
    liquibase-schema: public
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5445/school_project?currentSchema=public}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    change-log: db/changelog/db.changelog-master.yaml
  application.name: school_project
  web:
    locale: pt_BR
    localeResolver: fixed
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
springdoc:
  override-with-generic-response: false
  api-docs:
    enabled: true
  swagger-ui:
    server.list: ${SPRINGDOC_SWAGGER-UI_SERVER_LIST:http://localhost:8099/api/school-project}
    enabled: true
    doc-expansion: none
    operations-sorter: alpha
    tags-sorter: alpha
    filter: true
    path: /swagger-ui
    disable-swagger-default-url: true
    csrf.enabled: false
  default-produces-media-type: application/json
api:
  standard-error:
    trace: false
